# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [92]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [93]:
city_df = pd.read_csv("weather_data.csv")
city_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,nome,64.50,-165.41,69.01,55.0,1.0,8.05,US,1.592341e+09
1,1,margate,51.38,1.39,61.00,87.0,0.0,1.99,GB,1.592341e+09
2,2,portland,45.52,-122.68,64.00,72.0,75.0,11.41,US,1.592340e+09
3,3,macomb,40.46,-90.67,82.99,39.0,1.0,9.17,US,1.592340e+09
4,4,chuy,-33.70,-53.46,60.85,93.0,38.0,6.06,UY,1.592341e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [105]:
locations1 = city_df[["Lat", "Lng"]]
humidity = city_df["Humidity"].astype(float)

In [107]:
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations1, weights=humidity, 
                                 dissipating=False, max_intensity=225,
                                 point_radius=4)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [97]:
# Created new DF using boolean variables
weather_vac = city_df['Max Temp'] >= 70
weather2_vac = city_df['Max Temp'] < 80
wind_vac = city_df['Wind Speed'] < 10
cloud_vac = city_df['Cloudiness'] == 0
vacation_df = city_df[weather_vac & weather2_vac & wind_vac & cloud_vac]
vacation_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
69,78,kalivia,35.06,25.23,71.60,68.0,0.0,1.50,GR,1.592341e+09
152,166,poum,-20.23,164.02,73.11,77.0,0.0,9.55,NC,1.592341e+09
225,245,namibe,-15.20,12.15,71.06,68.0,0.0,1.59,AO,1.592341e+09
229,249,gat,31.61,34.76,75.99,47.0,0.0,5.01,IL,1.592341e+09
263,286,sao filipe,14.90,-24.50,77.43,78.0,0.0,6.64,CV,1.592341e+09
309,338,awbari,26.59,12.78,76.87,17.0,0.0,6.55,LY,1.592341e+09
312,341,poya,-21.35,165.15,71.10,75.0,0.0,3.44,NC,1.592341e+09
314,343,matadi,-5.82,13.45,74.97,80.0,0.0,5.21,CD,1.592341e+09
418,457,maba,24.68,113.60,73.87,88.0,0.0,3.00,CN,1.592341e+09
456,497,belaya gora,68.53,146.42,78.19,31.0,0.0,7.45,RU,1.592341e+09
466,508,uruzgan,32.83,66.00,70.00,20.0,0.0,4.12,AF,1.592341e+09
514,562,nioki,-2.72,17.68,74.59,56.0,0.0,2.08,CD,1.592341e+09
519,567,fereydun kenar,36.69,52.52,71.60,73.0,0.0,4.70,IR,1.592341e+09
537,587,caiaponia,-16.96,-51.81,70.63,64.0,0.0,6.13,BR,1.592341e+09
554,606,tafresh,34.69,50.01,71.71,23.0,0.0,5.84,IR,1.592341e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [98]:
hotel_df = vacation_df
hotel_df['Hotel Name'] = ""
hotel_df.head()

<ipython-input-98-b9baac8dfd90>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df['Hotel Name'] = ""

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
69,78,kalivia,35.06,25.23,71.60,68.0,0.0,1.50,GR,1.592341e+09,
152,166,poum,-20.23,164.02,73.11,77.0,0.0,9.55,NC,1.592341e+09,
225,245,namibe,-15.20,12.15,71.06,68.0,0.0,1.59,AO,1.592341e+09,
229,249,gat,31.61,34.76,75.99,47.0,0.0,5.01,IL,1.592341e+09,
263,286,sao filipe,14.90,-24.50,77.43,78.0,0.0,6.64,CV,1.592341e+09,

In [ ]:
# example URL for city: Kalivia
# https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=35.06,25.23&radius=5000&type=lodging&key=AIzaSyCqck2KHeS_VkvsgPYice6VuqCLLD3JfBk

In [99]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
#     "rankby": "distance",
    "type": "lodging",
    "key": g_key,
}
for index, row in hotel_df.iterrows():
    latitude = row['Lat']
    longitude = row['Lng']
    city = row['City']
    params['location'] = f'{latitude},{longitude}'
    print(f"Retrieving Results for Index [{index}] City: {city}.")
    response = requests.get(base_url, params=params).json()
    results = response['results']
    try:
        print(f'Closest Hotel in a 5,000 meter radius to the city is {results[0]["name"]}')
        hotel_df.loc[index, 'Hotel Name'] = results[0]["name"]
    except (KeyError, IndexError):
        print('No Hotels within 5,000 meters of locations.')
    print('-------------------')

Retrieving Results for Index [69] City: kalivia.
Closest Hotel in a 5,000 meter radius to the city is ΑΝΩ ΚΑΣΤΕΛΛΙΑΝΑ
-------------------
Retrieving Results for Index [152] City: poum.

C:\Users\Clay\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Closest Hotel in a 5,000 meter radius to the city is Gîte kajeon
-------------------
Retrieving Results for Index [225] City: namibe.
Closest Hotel in a 5,000 meter radius to the city is Hotel Chik Chik Namibe
-------------------
Retrieving Results for Index [229] City: gat.
Closest Hotel in a 5,000 meter radius to the city is רגע בנחת
-------------------
Retrieving Results for Index [263] City: sao filipe.
Closest Hotel in a 5,000 meter radius to the city is Tortuga B&B
-------------------
Retrieving Results for Index [309] City: awbari.
Closest Hotel in a 5,000 meter radius to the city is فندق أوباري
-------------------
Retrieving Results for Index [312] City: poya.
No Hotels within 5,000 meters of locations.
-------------------
Retrieving Results for Index [314] City: matadi.
Closest Hotel in a 5,000 meter radius to the city is Hotel Fortune
-------------------
Retrieving Results for Index [418] City: maba.
Closest Hotel in a 5,000 meter radius to the city is 康泰旅店
-------------------
Retrieving Results for Index [456] City: belaya gora.
No Hotels within 5,000 meters of locations.
-------------------
Retrieving Results for Index [466] City: uruzgan.
No Hotels within 5,000 meters of locations.
-------------------
Retrieving Results for Index [514] City: nioki.
No Hotels within 5,000 meters of locations.
-------------------
Retrieving Results for Index [519] City: fereydun kenar.
Closest Hotel in a 5,000 meter radius to the city is Khezer Shahr Tourist Hotel
-------------------
Retrieving Results for Index [537] City: caiaponia.
Closest Hotel in a 5,000 meter radius to the city is HOTEL PALACE AVENIDA
-------------------
Retrieving Results for Index [554] City: tafresh.
Closest Hotel in a 5,000 meter radius to the city is هتل و رستوران یاس سفید
-------------------

In [115]:
hotel_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
69,78,kalivia,35.06,25.23,71.60,68.0,0.0,1.50,GR,1.592341e+09,ΑΝΩ ΚΑΣΤΕΛΛΙΑΝΑ
152,166,poum,-20.23,164.02,73.11,77.0,0.0,9.55,NC,1.592341e+09,Gîte kajeon
225,245,namibe,-15.20,12.15,71.06,68.0,0.0,1.59,AO,1.592341e+09,Hotel Chik Chik Namibe
229,249,gat,31.61,34.76,75.99,47.0,0.0,5.01,IL,1.592341e+09,רגע בנחת
263,286,sao filipe,14.90,-24.50,77.43,78.0,0.0,6.64,CV,1.592341e+09,Tortuga B&B

In [104]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [114]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))